version: '3'

services:
#    client:
#        build:
#            context: .
#            dockerfile: devops/docker/client/Dockerfile
#            args:
#                DEPLOY: local
#        command: bash -c "cd /code/client && yarn start"
#        ports:
#            - "12342:3000"
#        volumes:
#            - fitness-code:/code

    server-ruby:
        build:
            context: .
            dockerfile: devops/docker/server-ruby/Dockerfile
            args:
                DEPLOY: local
        volumes:
            - fitness-code:/code
        ports:
            - "12343:3000"
        command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
        stdin_open: true
        tty: true

    proxy-nginx:
        build:
            context: .
            dockerfile: devops/docker/proxy-nginx/Dockerfile
            args:
                DEPLOY: local
        ports:
            - "12341:80"
        volumes:
            - fitness-code:/code

    mysql:
        build:
            context: .
            dockerfile: devops/docker/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "12340:3306"
        volumes:
            - ./devops/docker/mysql/data:/var/log/mysql:rw
        user: mysql

    redis:
        image: redis:6
        volumes:
            - fitness-code:/code
        ports:
            - "12342:6379"
        command: redis-server --appendonly yes

# https://qiita.com/kunit/items/36d9e5fa710ad26f8010
# https://forums.docker.com/t/nfs-native-support/48531/4
volumes:
    fitness-code:
      driver: local
      driver_opts:
        type: nfs
        o: addr=host.docker.internal,actimeo=1,nolock
        #      o: addr=addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
        device: ":${PWD}"