AllCops:
  Exclude:
    - bin/*
    - db/schema.rb

# 日本語コメント許可
AsciiComments:
  Enabled: false

# ダブルクォーテーションに統一
StringLiterals:
  EnforcedStyle: double_quotes

# ドキュメント
Style/Documentation:
  Exclude:
    - "db/migrate/**/*"

# メソッドの長さ
Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"

# AbcSize
Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"

# 行の長さ
Layout/LineLength:
  Exclude:
    - "config/initializers/**/*"